-- MySQL Script generated by MySQL Workbench
-- 05/16/15 18:05:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`author` (
  `authorName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`authorName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`news` (
  `idNews` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `circulation` INT(11) NULL DEFAULT NULL,
  `publishdate` DATE NULL DEFAULT NULL,
  `region` VARCHAR(45) NULL DEFAULT NULL,
  `authorName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idNews`),
  INDEX `fk_News_Author_idx` (`authorName` ASC),
  CONSTRAINT `fk_News_Author`
    FOREIGN KEY (`authorName`)
    REFERENCES `mydb`.`author` (`authorName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`new_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`new_view` (`idNews` INT, `region` INT, `circulation` INT);

-- -----------------------------------------------------
-- View `mydb`.`new_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`new_view`;
USE `mydb`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `mydb`.`new_view` AS select `mydb`.`news`.`idNews` AS `idNews`,`mydb`.`news`.`region` AS `region`,sum(`mydb`.`news`.`circulation`) AS `circulation` from `mydb`.`news` where (`mydb`.`news`.`publishdate` > (curdate() + interval -(1) year)) group by `mydb`.`news`.`region`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
